import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { createMetadata } from "@/shared/lib/createMetadata";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = createMetadata(
  "Create Next App",
  "Generated by create next app",
);

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth bg-[#f6f7f8]">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#f6f7f8]`}
      >
        {children}
      </body>
    </html>
  );
}
